name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag alecbrown/rust-flatbuffers:$(date +%s)
    - name: Login to Docker
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PWD }}
    - name: Push the Docker Image to hub.docker.com
      run: docker push alecbrown/rust-flatbuffers
    
